<?php

namespace App\Support;

class ExportLocale
{
    private const LOCALES = ['en', 'fr'];

    public function __construct(private readonly string $locale = 'en') {}

    public static function normalize(?string $locale): string
    {
        return in_array($locale, self::LOCALES, true) ? $locale : 'en';
    }

    public function code(): string
    {
        return $this->locale;
    }

    public function t(string $key): string
    {
        return self::strings()[$this->locale][$key] ?? self::strings()['en'][$key] ?? $key;
    }

    public function statusLabel(string $status): string
    {
        return self::strings()[$this->locale]['status'][$status]
            ?? self::strings()['en']['status'][$status]
            ?? $status;
    }

    public function categoryLabel(string $category): string
    {
        return self::strings()[$this->locale]['category'][$category]
            ?? self::strings()['en']['category'][$category]
            ?? $category;
    }

    public function sortLabel(string $sort): string
    {
        return self::strings()[$this->locale]['sort'][$sort]
            ?? self::strings()['en']['sort'][$sort]
            ?? $sort;
    }

    public function genderLabel(?string $gender): string
    {
        if ($gender === null || $gender === '') {
            return '';
        }

        return self::strings()[$this->locale]['genderValues'][$gender]
            ?? $gender;
    }

    public function csvHeaders(): array
    {
        return [
            $this->t('firstName'),
            $this->t('lastName'),
            $this->t('email'),
            $this->t('phone'),
            $this->t('gender'),
            $this->t('age'),
            $this->t('education'),
            $this->t('diplomaName'),
            $this->t('diplomaAverage'),
            $this->t('promotion'),
            $this->t('statusHeader'),
            $this->t('avgScore'),
            $this->t('categoryHeader'),
            $this->t('recruitmentDate'),
        ];
    }

    public function tableHeaders(): array
    {
        return [
            $this->t('name'),
            $this->t('email'),
            $this->t('phone'),
            $this->t('gender'),
            $this->t('age'),
            $this->t('education'),
            $this->t('diploma'),
            $this->t('statusHeader'),
            $this->t('avg'),
            $this->t('categoryHeader'),
            $this->t('date'),
        ];
    }

    public function promoCountLabel(int $count): string
    {
        if ($this->locale === 'fr') {
            return $count === 1 ? '1 candidat' : "{$count} candidats";
        }

        return $count === 1 ? '1 candidate' : "{$count} candidates";
    }

    public function promoHeaderRow(string $name, int $count): string
    {
        return sprintf($this->t('promoHeader'), $name, $this->promoCountLabel($count));
    }

    /** @return array<string, string> */
    private static function strings(): array
    {
        return [
            'en' => [
                'htmlLang' => 'en',
                'pageTitle' => 'All Candidates — CareerHub',
                'brand' => 'CareerHub Report',
                'allCandidates' => 'All Candidates',
                'subtitle' => 'Grouped by promotion · includes Active, Graduated, Dismissed, and Terminated candidates.',
                'exportedOn' => 'Exported on',
                'filtersApplied' => 'Filters applied:',
                'footer' => 'Generated by CareerHub · Cloud Marketing Hub',
                'unassigned' => 'Unassigned',
                'promoHeader' => 'Promotion: %s (%s)',
                'recruited' => 'Recruited',
                'yrs' => 'yrs',
                'scope' => 'All non-archived candidates (Active, Graduated, Dismissed, Terminated)',
                'firstName' => 'First Name',
                'lastName' => 'Last Name',
                'email' => 'Email',
                'phone' => 'Phone',
                'gender' => 'Gender',
                'age' => 'Age',
                'education' => 'Education',
                'diplomaName' => 'Diploma Name',
                'diplomaAverage' => 'Diploma Average',
                'promotion' => 'Promotion',
                'statusHeader' => 'Status',
                'avgScore' => 'Avg Score',
                'categoryHeader' => 'Category',
                'recruitmentDate' => 'Recruitment Date',
                'name' => 'Name',
                'diploma' => 'Diploma',
                'avg' => 'Avg',
                'date' => 'Date',
                'total' => 'Total',
                'search' => 'Search',
                'sortLabel' => 'Sort',
                'status' => [
                    'Active' => 'Active',
                    'Graduated' => 'Graduated',
                    'Dismissed' => 'Dismissed',
                    'Terminated' => 'Terminated',
                    'Archived' => 'Archived',
                ],
                'category' => [
                    'Excellent' => 'Excellent',
                    'Good' => 'Good',
                    'Passable' => 'Passable',
                    'Critical' => 'Critical',
                ],
                'sort' => [
                    'avg_desc' => 'Best Average',
                    'avg_asc' => 'Worst Average',
                    'name_asc' => 'Name A→Z',
                    'name_desc' => 'Name Z→A',
                    'date_desc' => 'Newest',
                    'date_asc' => 'Oldest',
                ],
                'genderValues' => [
                    'Homme' => 'Male',
                    'Femme' => 'Female',
                ],
            ],
            'fr' => [
                'htmlLang' => 'fr',
                'pageTitle' => 'Tous les candidats — CareerHub',
                'brand' => 'Rapport CareerHub',
                'allCandidates' => 'Tous les candidats',
                'subtitle' => 'Regroupés par promotion · inclut les candidats Actifs, Diplômés, Exclus et Résiliés.',
                'exportedOn' => 'Exporté le',
                'filtersApplied' => 'Filtres appliqués :',
                'footer' => 'Généré par CareerHub · Cloud Marketing Hub',
                'unassigned' => 'Non assigné',
                'promoHeader' => 'Promotion : %s (%s)',
                'recruited' => 'Recruté le',
                'yrs' => 'ans',
                'scope' => 'Tous les candidats non archivés (Actifs, Diplômés, Exclus, Résiliés)',
                'firstName' => 'Prénom',
                'lastName' => 'Nom',
                'email' => 'E-mail',
                'phone' => 'Téléphone',
                'gender' => 'Genre',
                'age' => 'Âge',
                'education' => 'Formation',
                'diplomaName' => 'Intitulé du diplôme',
                'diplomaAverage' => 'Moyenne du diplôme',
                'promotion' => 'Promotion',
                'statusHeader' => 'Statut',
                'avgScore' => 'Moy. score',
                'categoryHeader' => 'Catégorie',
                'recruitmentDate' => 'Date de recrutement',
                'name' => 'Nom',
                'diploma' => 'Diplôme',
                'avg' => 'Moy.',
                'date' => 'Date',
                'total' => 'Total',
                'search' => 'Recherche',
                'sortLabel' => 'Tri',
                'status' => [
                    'Active' => 'Actif',
                    'Graduated' => 'Diplômé',
                    'Dismissed' => 'Exclu',
                    'Terminated' => 'Résilié',
                    'Archived' => 'Archivé',
                ],
                'category' => [
                    'Excellent' => 'Excellent',
                    'Good' => 'Bien',
                    'Passable' => 'Passable',
                    'Critical' => 'Critique',
                ],
                'sort' => [
                    'avg_desc' => 'Meilleure moyenne',
                    'avg_asc' => 'Moyenne la plus basse',
                    'name_asc' => 'Nom A→Z',
                    'name_desc' => 'Nom Z→A',
                    'date_desc' => 'Plus récent',
                    'date_asc' => 'Plus ancien',
                ],
                'genderValues' => [
                    'Homme' => 'Homme',
                    'Femme' => 'Femme',
                ],
            ],
        ];
    }
}
