/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromotionsIndexRouteImport } from './routes/promotions.index'
import { Route as PromotionsIdRouteImport } from './routes/promotions.$id'
import { Route as CandidatesIdRouteImport } from './routes/candidates.$id'
import { Route as PromotionsIdCalendarRouteImport } from './routes/promotions.$id.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIndexRoute = PromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIdRoute = PromotionsIdRouteImport.update({
  id: '/promotions/$id',
  path: '/promotions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIdCalendarRoute = PromotionsIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PromotionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/promotions/$id': typeof PromotionsIdRouteWithChildren
  '/promotions/': typeof PromotionsIndexRoute
  '/promotions/$id/calendar': typeof PromotionsIdCalendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/promotions/$id': typeof PromotionsIdRouteWithChildren
  '/promotions': typeof PromotionsIndexRoute
  '/promotions/$id/calendar': typeof PromotionsIdCalendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/promotions/$id': typeof PromotionsIdRouteWithChildren
  '/promotions/': typeof PromotionsIndexRoute
  '/promotions/$id/calendar': typeof PromotionsIdCalendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidates/$id'
    | '/promotions/$id'
    | '/promotions/'
    | '/promotions/$id/calendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidates/$id'
    | '/promotions/$id'
    | '/promotions'
    | '/promotions/$id/calendar'
  id:
    | '__root__'
    | '/'
    | '/candidates/$id'
    | '/promotions/$id'
    | '/promotions/'
    | '/promotions/$id/calendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  PromotionsIdRoute: typeof PromotionsIdRouteWithChildren
  PromotionsIndexRoute: typeof PromotionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/': {
      id: '/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof PromotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/$id': {
      id: '/promotions/$id'
      path: '/promotions/$id'
      fullPath: '/promotions/$id'
      preLoaderRoute: typeof PromotionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/$id/calendar': {
      id: '/promotions/$id/calendar'
      path: '/calendar'
      fullPath: '/promotions/$id/calendar'
      preLoaderRoute: typeof PromotionsIdCalendarRouteImport
      parentRoute: typeof PromotionsIdRoute
    }
  }
}

interface PromotionsIdRouteChildren {
  PromotionsIdCalendarRoute: typeof PromotionsIdCalendarRoute
}

const PromotionsIdRouteChildren: PromotionsIdRouteChildren = {
  PromotionsIdCalendarRoute: PromotionsIdCalendarRoute,
}

const PromotionsIdRouteWithChildren = PromotionsIdRoute._addFileChildren(
  PromotionsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  PromotionsIdRoute: PromotionsIdRouteWithChildren,
  PromotionsIndexRoute: PromotionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
